/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.pkg8_joselagos;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author tali_
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop_menu = new javax.swing.JPopupMenu();
        jm_despedir = new javax.swing.JMenuItem();
        jm_ascender = new javax.swing.JMenuItem();
        jd_tabla = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jt_gerente_general = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_ID = new javax.swing.JTextField();
        tf_contra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        anadir = new javax.swing.JButton();
        cb_anadir = new javax.swing.JComboBox<>();
        CrearGerenete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jt_id = new javax.swing.JTextField();
        jt_contra = new javax.swing.JTextField();
        jt_salario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_salario = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_listar = new javax.swing.JTree();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cb_PARA = new javax.swing.JComboBox<>();
        cb_DE = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        cb_type = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jm_despedir.setText("Despedir");
        jm_despedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_despedirActionPerformed(evt);
            }
        });
        pop_menu.add(jm_despedir);

        jm_ascender.setText("ascender");
        jm_ascender.setToolTipText("");
        jm_ascender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_ascenderActionPerformed(evt);
            }
        });
        pop_menu.add(jm_ascender);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DE", "PARA", "Mensajes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jd_tablaLayout = new javax.swing.GroupLayout(jd_tabla.getContentPane());
        jd_tabla.getContentPane().setLayout(jd_tablaLayout);
        jd_tablaLayout.setHorizontalGroup(
            jd_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jd_tablaLayout.setVerticalGroup(
            jd_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_tablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel1.setText("Gerente General");

        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Empleados");

        tf_nombre.setEnabled(false);

        tf_ID.setEnabled(false);

        tf_contra.setEnabled(false);

        jLabel4.setText("Contrasena");

        jLabel5.setText("Jefe");

        anadir.setText("Anadir");
        anadir.setEnabled(false);
        anadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anadirMouseClicked(evt);
            }
        });

        cb_anadir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cb_anadir.setEnabled(false);

        CrearGerenete.setText("Crear Gerente General");
        CrearGerenete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearGereneteMouseClicked(evt);
            }
        });

        jLabel6.setText("ID");

        jLabel8.setText("Salario");

        jLabel10.setText("Contrasena");

        jLabel7.setText("ID");

        jLabel9.setText("Salario");

        jLabel11.setText("puesto");

        tf_salario.setEnabled(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Gerente" }));
        jComboBox1.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CrearGerenete)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(57, 57, 57)
                                .addComponent(jt_contra, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(jt_gerente_general))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(40, 40, 40))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tf_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(tf_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel11))
                                            .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(anadir)
                                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(9, 9, 9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(83, 83, 83)
                                .addComponent(jt_salario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(112, 112, 112)
                                .addComponent(jt_id)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jt_gerente_general, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jt_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jt_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CrearGerenete)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tf_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cb_anadir))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(anadir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Crear", jPanel1);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("raiz");
        jt_listar.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_listarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_listar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("Listar", jPanel2);

        jLabel12.setText("DE");

        jLabel13.setText("PARA");

        jLabel14.setText("Mensaje");

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane2.setViewportView(ta_mensaje);

        jLabel15.setText("Type");

        cb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "BroadCast", " " }));
        cb_type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_typeItemStateChanged(evt);
            }
        });

        jButton1.setText("ENVIAR");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Ver todos los mensajes");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(79, 79, 79))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(35, 35, 35)
                                .addComponent(cb_DE, 0, 502, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_PARA, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_PARA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cb_DE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mensajes", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anadirMouseClicked
        int a = 0;
        int b = 0;
        Empleados p = new Empleados(tf_nombre.getText(), Integer.parseInt(tf_ID.getText()), tf_contra.getText(), (Empleados) cb_anadir.getSelectedItem(), Double.parseDouble(tf_salario.getText()), jComboBox1.getSelectedItem().toString());
        Empleados k = (Empleados) cb_anadir.getSelectedItem();
        k.getListaempleados().add(p);
        lista.add(p);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_anadir.getModel();
        if (p.getPuesto().equals("Gerente")) {
            modelo.addElement(p);
        }
        cb_anadir.setModel(modelo);
        tf_nombre.setText("");
        tf_ID.setText("");
        tf_contra.setText("");
        tf_salario.setText("");

    }//GEN-LAST:event_anadirMouseClicked

    private void CrearGereneteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearGereneteMouseClicked
        lista.add(new Empleados(jt_gerente_general.getText(), Integer.parseInt(jt_id.getText()), jt_contra.getText(), null, Integer.parseInt(jt_salario.getText()), "Gerente General"));
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(lista.toArray());
        cb_anadir.setModel(modelo);
        CrearGerenete.setEnabled(false);
        jt_id.setText("");
        jt_contra.setText("");
        jt_salario.setText("");
        jt_id.setEnabled(false);
        jt_contra.setEnabled(false);
        jt_salario.setEnabled(false);
        jt_gerente_general.setEnabled(false);
        tf_nombre.setEnabled(true);
        tf_ID.setEnabled(true);
        tf_contra.setEnabled(true);
        tf_salario.setEnabled(true);
        cb_anadir.setEnabled(true);
        jComboBox1.setEnabled(true);
        anadir.setEnabled(true);
    }//GEN-LAST:event_CrearGereneteMouseClicked

    private void jt_listarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_listarMouseClicked
        if (evt.isMetaDown()) {
            pop_menu.setVisible(true);
            pop_menu.show(evt.getComponent(), evt.getX(), evt.getY());

        }
    }//GEN-LAST:event_jt_listarMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        if (jTabbedPane1.getSelectedIndex() == 1) {
            String name = lista.get(0).getNombre();
            Empleados p = new Empleados();
            int a = lista.size();
            for (a = lista.size() - 1; a >= 0; a--) {
                if (lista.get(a).getNombre().equals(name)) {
                    p = lista.get(a);
                }
            }

            DefaultMutableTreeNode raiz = new DefaultMutableTreeNode(p);
            DefaultTreeModel model = new DefaultTreeModel(raiz);
            jt_listar.setModel(model);
            String nombre = null;
            String material = null;
            int num = 0;
            Empleados padre = null;
            if (p.getListaempleados().size() > 0) {
                nombre = null;
                material = null;
                num = 0;
                padre = null;
                Print(p, (DefaultMutableTreeNode) raiz.getRoot());
            }
            if (cb_type.getSelectedItem().toString().equals("BroadCast")) {
                ArrayList<Empleados> gerentes = new ArrayList();
                for (int b = 0; b < lista.size(); b++) {
                    if (lista.get(b).getPuesto().equals("Gerente")) {
                        gerentes.add(lista.get(b));
                    }
                }
                DefaultComboBoxModel modelo = new DefaultComboBoxModel(gerentes.toArray());
                cb_DE.setModel(modelo);
                cb_PARA.setEnabled(false);
            } else {
                DefaultComboBoxModel modelo = new DefaultComboBoxModel(lista.toArray());
                cb_DE.setModel(modelo);
                cb_PARA.setModel(modelo);
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jm_despedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_despedirActionPerformed
        Object v1 = jt_listar.getSelectionPath().getLastPathComponent();
        nodo_el = (DefaultMutableTreeNode) v1;
        Empleados temp = (Empleados) nodo_el.getUserObject();
        Empleados jefe = temp.getJefe();
        if (temp.getListaempleados().size() > 0) {
            Empleados newboss = temp.getListaempleados().get(0);
            for (int a = temp.getListaempleados().size() - 1; a >= 0; a--) {
                System.out.println(a);
                System.out.println(temp.getListaempleados().size());
                if (a == 0) {
                    temp.getListaempleados().get(a).setJefe(jefe);
                    Empleados sexy = temp.getListaempleados().get(a);
                    jefe.getListaempleados().add(sexy);
                } else {
                    temp.getListaempleados().get(a).setJefe(newboss);
                    Empleados newchild = temp.getListaempleados().get(a);
                    newboss.getListaempleados().add(newchild);
                }
            }
        }
        for (int a = 0; a < lista.size(); a++) {
            if (temp.equals(lista.get(a))) {
                lista.remove(a);
            }
        }
        for (int a = 0; a < jefe.getListaempleados().size(); a++) {
            if (temp.equals(jefe.getListaempleados().get(a))) {
                jefe.getListaempleados().remove(a);
            }
        }
        DefaultTreeModel m = (DefaultTreeModel) jt_listar.getModel();
        m.removeNodeFromParent(nodo_el);
        String name = lista.get(0).getNombre();
        Empleados p = new Empleados();
        int a = lista.size();
        for (a = lista.size() - 1; a >= 0; a--) {
            if (lista.get(a).getNombre().equals(name)) {
                p = lista.get(a);
            }
        }

        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode(p);
        DefaultTreeModel model = new DefaultTreeModel(raiz);
        jt_listar.setModel(model);
        String nombre = null;
        String material = null;
        int num = 0;
        Empleados padre = null;
        if (p.getListaempleados().size() > 0) {
            nombre = null;
            material = null;
            num = 0;
            padre = null;
            Print(p, (DefaultMutableTreeNode) raiz.getRoot());
        }
    }//GEN-LAST:event_jm_despedirActionPerformed

    private void cb_typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_typeItemStateChanged
        if (cb_type.getSelectedItem().toString().equals("BroadCast")) {
            ArrayList<Empleados> gerentes = new ArrayList();
            for (int b = 0; b < lista.size(); b++) {
                if (lista.get(b).getPuesto().equals("Gerente") || lista.get(b).getPuesto().equals("Gerente General")) {
                    gerentes.add(lista.get(b));
                }

            }
            DefaultComboBoxModel modelo1 = new DefaultComboBoxModel(gerentes.toArray());
            cb_DE.setModel(modelo1);
            cb_PARA.setEnabled(false);
        } else {
            DefaultComboBoxModel modelo = new DefaultComboBoxModel(lista.toArray());
            DefaultComboBoxModel modelo1 = new DefaultComboBoxModel(lista.toArray());
            cb_DE.setModel(modelo1);
            cb_PARA.setModel(modelo);
            cb_PARA.setEnabled(true);
        }

    }//GEN-LAST:event_cb_typeItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Mensaje m = new Mensaje();
        if (cb_type.getSelectedItem().toString().equals("Normal")) {
            m = new Mensaje(ta_mensaje.getText(), cb_DE.getSelectedItem().toString(), cb_PARA.getSelectedItem().toString());
            listam.add(new Mensaje(ta_mensaje.getText(), cb_DE.getSelectedItem().toString(), cb_PARA.getSelectedItem().toString()));
        }
        if (cb_type.getSelectedItem().toString().equals("BroadCast")) {
            Mensaje mensaje = new Mensaje();
            ArrayList<Empleados> empleados = ((Empleados) cb_DE.getSelectedItem()).getListaempleados();
            m = new Mensaje(ta_mensaje.getText(), cb_DE.getSelectedItem().toString(), empleados.toString());
            listam.add(new Mensaje(ta_mensaje.getText(), cb_DE.getSelectedItem().toString(), empleados.toString()));
        }
        adminMensajes ap = new adminMensajes("./admin.jjj");
        ap.cargarArchivo();
        ap.setMensaje(m);
        ap.escribirArchivo();
        Codificar(m);
        ta_mensaje.setText("");

    }//GEN-LAST:event_jButton1MouseClicked

    private void jm_ascenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_ascenderActionPerformed
        Object v1 = jt_listar.getSelectionPath().getLastPathComponent();
        nodo_el = (DefaultMutableTreeNode) v1;
        Empleados temp = (Empleados) nodo_el.getUserObject();
        Empleados jefe = temp.getJefe();
        Empleados newjefe = jefe.getJefe();
        newjefe.getListaempleados().add(temp);
        for (int a = 0; a < jefe.getListaempleados().size(); a++) {
            if (temp.equals(jefe.getListaempleados().get(a))) {
                jefe.getListaempleados().remove(a);
            }
        }
        DefaultTreeModel m = (DefaultTreeModel) jt_listar.getModel();
        String name = lista.get(0).getNombre();
        Empleados p = new Empleados();
        int a = lista.size();
        for (a = lista.size() - 1; a >= 0; a--) {
            if (lista.get(a).getNombre().equals(name)) {
                p = lista.get(a);
            }
        }

        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode(p);
        DefaultTreeModel model = new DefaultTreeModel(raiz);
        jt_listar.setModel(model);
        String nombre = null;
        String material = null;
        int num = 0;
        Empleados padre = null;
        if (p.getListaempleados().size() > 0) {
            nombre = null;
            material = null;
            num = 0;
            padre = null;
            Print(p, (DefaultMutableTreeNode) raiz.getRoot());
        }
    }//GEN-LAST:event_jm_ascenderActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
            jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DE", "PARA", "Mensajes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
            for(Mensaje t : listam){
                  Object row[] = {t.getDe(),t.getPara(),t.getMensaje()};
            DefaultTableModel m = (DefaultTableModel)jTable1.getModel();
            m.addRow(row);
            jTable1.setModel(m);
            jd_tabla.setModal(true);
            jd_tabla.pack();
            jd_tabla.setLocationRelativeTo(this);
            jd_tabla.setVisible(true);
            }
    }//GEN-LAST:event_jButton2MouseClicked
    public void Print(Empleados p, DefaultMutableTreeNode nodo) {
        try {
            ArrayList<Empleados> lista = new ArrayList();
            for (Empleados f : p.getListaempleados()) {
                lista.add(f);
            }
            for (Empleados f : lista) {
                if (f.getListaempleados().size() > 0) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(f);
                    nodo.add(n);
                    Print(f, n);
                } else {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(f);
                    nodo.add(n);
                }
            }
        } catch (Exception e) {
        }
    }

    public void Codificar(Mensaje m) {
        String[] count = new String[m.getMensaje().length() - 1];
        count = m.getMensaje().split("(?!^)");
        ArrayList<codificacion> listaj = new ArrayList();
        for (String t : count) {
            int x = 0;
            for (String t2 : count) {
                if (t.equals(t2)) {
                    x++;
                }
            }
            listaj.add(new codificacion(t, x));
        }
        for (int a = 0; a < listaj.size(); a++) {
            for (int b = 0; b < listaj.size(); b++) {
                if (listaj.get(a).getLetra().equals(listaj.get(b).getLetra())) {
                    listaj.remove(a);
                }
            }
        }
        for (int x = 0; x < listaj.size(); x++) {
            for (int i = 0; i < listaj.size() - x - 1; i++) {
                if (listaj.get(i).getNumero() < listaj.get(i + 1).getNumero()) {
                    int tmp = listaj.get(i + 1).getNumero();
                    String tmp2 =  listaj.get(i + 1).getLetra();
                    listaj.get(i + 1).setNumero(listaj.get(i).getNumero());
                    listaj.get(i + 1).setLetra(listaj.get(i).getLetra());
                    listaj.get(i).setNumero(tmp);
                    listaj.get(i).setLetra(tmp2);
                }
            }
        }

        System.out.println(listaj.toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearGerenete;
    private javax.swing.JButton anadir;
    private javax.swing.JComboBox<String> cb_DE;
    private javax.swing.JComboBox<String> cb_PARA;
    private javax.swing.JComboBox<String> cb_anadir;
    private javax.swing.JComboBox<String> cb_type;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JDialog jd_tabla;
    private javax.swing.JMenuItem jm_ascender;
    private javax.swing.JMenuItem jm_despedir;
    private javax.swing.JTextField jt_contra;
    private javax.swing.JTextField jt_gerente_general;
    private javax.swing.JTextField jt_id;
    private javax.swing.JTree jt_listar;
    private javax.swing.JTextField jt_salario;
    private javax.swing.JPopupMenu pop_menu;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTextField tf_ID;
    private javax.swing.JTextField tf_contra;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_salario;
    // End of variables declaration//GEN-END:variables
ArrayList<Empleados> lista = new ArrayList();
    String name;
    DefaultMutableTreeNode nodo_el;
    ArrayList<Mensaje> listam = new ArrayList();
    ArrayList<codificacion> listacod = new ArrayList();
}
